go_library(
    name = "async",
    srcs = [
        "async_awaitable_t.go",
        "async_r.go",
        "async_result_t.go",
        "async_runner.go",
        "async_source.go",
        "async_string_r.go",
    ],
)
